### ISSUE TITLE
Separate `-g` groups funcrtionality into a separate function

### ISSUE THREAD

**Issue by xenithorb** [apptio/kube-config#17]
#8 should be separated into a function as presently it's tucked away procedurally in the `handleCallback` function and erroneously exits (thinking was because we're done after it prints) and due to this exit clobbers the existing configuration. 

So, if a user runs `kube-config -g` and  previously had a working configuration for a particular tier, they will now have an empty file.

**Comment by cspargo-apptio** [comment]
archiving this project
