### ISSUE TITLE
Refactor singular RootCmd + flags into separate cobra commands + flags 

### ISSUE THREAD

**Issue by xenithorb** [apptio/kube-config#9]
## Objective
Refactor using cobra commands and flags to clearly and cleanly define verbs for kube-config. For a while, if not indefinitely, the no verb default should still generate a valid YAML and accept the `--tier` flag among others.

### Changes
* `kube-config [login]` (also default/null/no verb)
  * `kube-config login [-t|--tier=<tier>] [-d|--debug] [-c|--cluster=<cluster>] [-n|namespace] [-o|--output=<file>] ...` 
* `kube-config list`
  * `kube-config list tiers` - list configured tiers 
  * `kube-config list groups` - list remote AD groups
  * `kube-config list config` - prints config 

### Additions (New!)
* `kube-config set`
  * `kube-config set cluster <cluster> [-n|--namespace=<namespace>] [-u|--username]` - sets persistent defaults for cluster
  * `kube-config set username <username>` - sets default username
  * `kube-config set configpath <directory>` - sets default output dir

**Comment by cspargo-apptio** [comment]
archiving this project
